from losses.cluster_consistency_loss import ClusterConsistencyLoss
from losses.entropy import EntropyRegularization, cluster_entropy, batch_entropy
from losses.representation_loss import RepresentationAlignmentLoss
